import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import type { SimplePool } from "nostr-tools/pool";
import { finalizeEvent } from "nostr-tools/pure";
import { watchCode as signedWatchCode, watchCopy, type OnCall, type ResponsePayload } from "@navcom/core";
import { loadOrCreateKeypair, type Keypair } from "../shared/identity.js";
import { sealResponse } from "../shared/crypto.js";
import { KIND_RESPONSE, KIND_WATCH_STATE } from "../shared/kinds.js";

/**
 * The escalation executor's own key (decided 2026-10-07, G3).
 *
 * The watch key is held by the daemon, which the agent runs beside, and by every squad member and
 * everybody who ever was one. A phone that ended a `Distress` on any answer the watch key signed
 * could be told "a person has it" by any of them. So the executor holds a key nobody else does,
 * signs every response with it, and a phone handed that key ends a `Distress` only on an answer it
 * signed (`escalation.spec.md`, *The executor has a key of its own*; *Who may close a Distress*).
 *
 * **It is only as separate as the file it lives in.** A key the daemon's user can read is a key the
 * agent can sign "a person has it" with, and a phone given it believes that over anything else. So
 * this module also says who can read it, and startup and `--check` say it out loud.
 */

export interface ExecutorKey extends Keypair {
  path: string;
  /** True when this call made it: the executor's first start, as the user it runs as. */
  created: boolean;
}

/**
 * Loads the executor's key, or makes it: `0600`, owned by whoever runs this process, in a directory
 * only they can enter. That is the setup step -- the key is generated by the user the executor runs as,
 * and by nobody else -- so there is nothing to copy onto the box and nothing to type.
 *
 * **Only the long-running start may make one, and only as a user of its own** ({@link whyNotMake}).
 * `--check` and `--drill` never do: a key made by whoever happened to run those would be born readable
 * by that user, and a later `chown` would make it look clean.
 */
export function loadExecutorKey(path: string): ExecutorKey {
  const created = !existsSync(path);
  return { ...loadOrCreateKeypair(path), path, created };
}

/**
 * The watch key, loaded and never made [review: box safety].
 *
 * The daemon makes it on its first start. One made here would be a new watch that no phone knows: the
 * executor would subscribe for Distress addressed to a key nobody sends to, and page for nothing --
 * no ladder, no "nobody is coming" -- while it looked healthy. A copy that was never made, or a path
 * mistyped, stops the executor instead, which a supervisor and a journal show.
 */
export function loadWatchKey(path: string): Keypair {
  if (!existsSync(path)) {
    throw new Error(
      `there is nothing at ${path}. The daemon makes the watch key on its first start, and the executor ` +
        "needs that same key -- a copy this user can read. It never makes one: a new key would be a watch no phone knows",
    );
  }
  return loadOrCreateKeypair(path);
}

/**
 * Why the executor must not make its key here, or null when it may: only where `daemon_user` names a
 * user of this machine who is neither this process's user nor root. A key made anywhere else is one the
 * daemon -- and the agent beside it -- could read from its first moment.
 */
export function whyNotMake(who: KeyReaders): string | null {
  if (who.daemonUser === null) {
    return "daemon_user is not set in [identity], so nothing can confirm the daemon's user could not read it";
  }
  if (who.daemonUid === null) return `daemon_user "${who.daemonUser}" is not a user on this machine`;
  if (who.daemonUid === 0) return `daemon_user is root (${who.daemonUser}), which can read every file on this machine`;
  if (who.executorUid !== null && who.executorUid === who.daemonUid) {
    return `this executor runs as the daemon's user (${who.daemonUser}), so the daemon could read it`;
  }
  return null;
}

/** Who this process is, and who `daemon_user` names, read from this machine. */
export function readersHere(daemonUser: string | undefined): KeyReaders {
  return {
    executorUid: typeof process.getuid === "function" ? process.getuid() : null,
    daemonUser: daemonUser ?? null,
    daemonUid: daemonUser === undefined ? null : resolveUid(daemonUser),
  };
}

/**
 * Every key this executor's own accountability log names as the escalation actor, other than `known`.
 *
 * The log outlives the key file: it records the executor's key as the actor of everything it does. So
 * a key about to be made where the log already names another one is a replacement -- a reinstall that
 * wiped the key, a restore that missed it, a path changed -- and every phone handed the old one can no
 * longer end a `Distress`. Read as text, without opening the log for writing; a log that cannot be read
 * says nothing.
 */
export function earlierExecutorKeys(logPath: string, known: readonly string[]): string[] {
  let text: string;
  try {
    text = readFileSync(logPath, "utf8");
  } catch {
    return [];
  }
  const found = new Set<string>();
  for (const line of text.split("\n")) {
    if (!line.trim()) continue;
    try {
      const entry = JSON.parse(line) as { actor?: { kind?: string; callsign?: string; pubkey?: string } };
      const pubkey = entry.actor?.pubkey;
      if (entry.actor?.callsign === "escalation" && typeof pubkey === "string" && /^[0-9a-f]{64}$/.test(pubkey)) found.add(pubkey);
    } catch {
      /* a torn line says nothing */
    }
  }
  for (const k of known) found.delete(k);
  return [...found];
}

/** What is kept beside an executor key made to replace one the log names, until a person says otherwise. */
export interface Replaced {
  /** Unix seconds the new key was made. */
  at: number;
  /** The keys the log named before it. */
  replaces: string[];
}

/** Where {@link Replaced} is kept: beside the key, in the directory only the executor's user can enter. */
export function replacedPath(keyPath: string): string {
  return `${keyPath}.replaced`;
}

export function writeReplaced(keyPath: string, record: Replaced): void {
  writeFileSync(replacedPath(keyPath), JSON.stringify(record) + "\n", { mode: 0o600 });
}

/** The replacement record, while it stands; null once a person has removed it, or if it never existed. */
export function readReplaced(keyPath: string): Replaced | null {
  try {
    const raw = JSON.parse(readFileSync(replacedPath(keyPath), "utf8")) as Partial<Replaced>;
    return { at: typeof raw.at === "number" ? raw.at : 0, replaces: Array.isArray(raw.replaces) ? raw.replaces.map(String) : [] };
  } catch {
    return existsSync(replacedPath(keyPath)) ? { at: 0, replaces: [] } : null;
  }
}

/** The words for a key made to replace another, said at every start and by `--check` while the record stands. */
export function replacedLines(keyPath: string, newKey: string, record: Replaced): string[] {
  const old = record.replaces.map((k) => k.slice(0, 8)).join(", ") || "an earlier key";
  return [
    `THIS IS A NEW EXECUTOR KEY (${newKey.slice(0, 8)}). This executor signed as ${old} before, and that`,
    "key is gone. Every phone handed it ends no Distress on anything this box sends until it is handed",
    "the new watch code. Restore the old key from a backup if you have one. Otherwise hand every operator",
    `the new code, and then remove ${replacedPath(keyPath)}.`,
  ];
}

/**
 * The roster entries whose key is the watch key or the executor's own [review: box safety]. Neither is a
 * person's: the executor refuses an acknowledgement or a wake from either, and `--check` fails on them.
 */
export function boxKeysOnRoster(oncall: readonly { declaration: OnCall }[], boxKeys: readonly string[]): string[] {
  return oncall
    .filter((e) => e.declaration.author.pubkey !== undefined && boxKeys.includes(e.declaration.author.pubkey))
    .map((e) => e.declaration.author.callsign ?? e.declaration.author.pubkey!.slice(0, 8));
}

/**
 * The watch code a phone is handed: the watch's address, its relays, and the executor's own key, **signed
 * by the watch key** and dated.
 *
 * Made by `@navcom/core`'s `watchCode`, the one maker and reader of the format, so what the box prints is
 * what the Field Terminal reads: a link, so a phone's camera opens it, with `watch=1`, `w`, each `r`, `x`,
 * `t` and `s`, the watch key's signature over all of it. A box has no holders.
 * A phone fills in nothing from a code its watch did not sign, so a stranger cannot hand an operator a key
 * of their own as this watch's escalation key.
 *
 * The executor's key is never typed into a phone -- a mistyped key on the curve cannot be told from a real
 * one, and no answer could then end a `Distress` -- so this is the one way the box hands it over.
 */
export function watchCode(
  watch: Keypair,
  relays: readonly string[],
  executorPubkey?: string,
  issuedAt: number = Math.floor(Date.now() / 1000),
): string {
  const listed = [...new Set(relays.map((r) => r.trim()).filter(Boolean))];
  const executor = executorPubkey?.toLowerCase();
  return signedWatchCode({ pubkey: watch.pubkey, relays: listed, holders: [], ...(executor ? { executor } : {}) }, watch.secretKey, issuedAt);
}

/**
 * Whether any relay holds a watch state (`10910`) signed by `pubkey` -- the one way this process can see
 * that the key it was given is the daemon's. A copy of the wrong file leaves the executor deaf to every
 * Distress meant for this watch, and nothing else says so. False when none does -- or none answered,
 * which a daemon that is not running yet looks like too, so the caller says it rather than failing.
 */
export async function watchStateSeen(pool: SimplePool, urls: readonly string[], pubkey: string, maxWait = 5_000): Promise<boolean> {
  const found = await pool.querySync([...new Set(urls)], { kinds: [KIND_WATCH_STATE], authors: [pubkey], limit: 1 }, { maxWait });
  return found.some((e) => e.pubkey === pubkey);
}

/** What the file system says about the key file: its permission bits and its owner. */
export interface KeyFileFacts {
  mode: number;
  uid: number;
}

export interface KeyReaders {
  /** The user this executor runs as, or null where the platform has no uids. */
  executorUid: number | null;
  /** `daemon_user` as configured, or null when it is not. */
  daemonUser: string | null;
  /** That user's uid, or null when it is not configured or is not a user here. */
  daemonUid: number | null;
}

/**
 * Everything wrong with who can read the executor's key, in words a Stationkeeper can act on. Empty
 * is the only good answer. `escalation.spec.md`, *Only the executor can read its key*.
 */
export function keyFileProblems(path: string, facts: KeyFileFacts, who: KeyReaders): string[] {
  const problems: string[] = [];
  if ((facts.mode & 0o077) !== 0) {
    problems.push(
      `other users can read or change it (mode ${(facts.mode & 0o777).toString(8).padStart(3, "0")}) -- run: chmod 600 ${path}`,
    );
  }
  if (who.executorUid !== null && facts.uid !== who.executorUid) {
    problems.push(
      `it is owned by uid ${facts.uid}, not by the user this executor runs as (uid ${who.executorUid}) -- whoever owns a file can read it`,
    );
  }
  if (who.daemonUser === null) {
    problems.push(
      "daemon_user is not set in [identity], so nothing can confirm the daemon's user cannot read it -- set it to the user the daemon runs as",
    );
  } else if (who.daemonUid === null) {
    problems.push(`daemon_user "${who.daemonUser}" is not a user on this machine -- set it to the user the daemon runs as`);
  } else {
    if (who.daemonUid === 0) {
      problems.push(
        `the daemon runs as root (${who.daemonUser}), which can read every file on this machine, this one included -- ` +
          "run the daemon as an unprivileged user",
      );
    }
    if (facts.uid === who.daemonUid) {
      problems.push(`it is owned by the daemon's user (${who.daemonUser}) -- the daemon, and the agent beside it, can read it`);
    }
    if (who.executorUid === who.daemonUid) {
      problems.push(
        `this executor runs as the daemon's user (${who.daemonUser}) -- the daemon, and the agent beside it, can read every file it can. ` +
          "Run the executor as a user of its own",
      );
    }
  }
  return problems;
}

/** A user name or uid as a uid, or null when this machine has no such user. Never a shell. */
export function resolveUid(user: string): number | null {
  if (/^\d+$/.test(user)) return Number(user);
  try {
    const out = execFileSync("id", ["-u", user], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
    return /^\d+$/.test(out) ? Number(out) : null;
  } catch {
    return null;
  }
}

/** Who can read the key at `path`, as `keyFileProblems` judges it, read from this machine. */
export function checkKeyFile(path: string, daemonUser: string | undefined): string[] {
  let facts: KeyFileFacts;
  try {
    const stat = statSync(path);
    facts = { mode: stat.mode, uid: stat.uid };
  } catch (err: unknown) {
    return [`it could not be read: ${String(err)}`];
  }
  return keyFileProblems(path, facts, readersHere(daemonUser));
}

/** Groups whose members can usually become root. */
const ADMIN_GROUPS = ["sudo", "wheel", "admin"];

/**
 * What the file check cannot see: a daemon user in a group that can usually become root. Said, never
 * failed on -- the reference box runs the daemon as its owner's login user, and whether `sudo` asks that
 * user for a password is not something a file can show. Null where `id` says nothing of the kind.
 */
export function daemonAdminNote(daemonUser: string | undefined): string | null {
  if (daemonUser === undefined) return null;
  let groups: string[];
  try {
    groups = execFileSync("id", ["-Gn", daemonUser], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim().split(/\s+/);
  } catch {
    return null;
  }
  const admin = groups.filter((g) => ADMIN_GROUPS.includes(g));
  if (admin.length === 0) return null;
  return (
    `the daemon's user (${daemonUser}) is in ${admin.join(", ")}: if sudo asks it no password, the daemon -- and the ` +
    `agent beside it -- can read this key through sudo. Check with: sudo -l -U ${daemonUser}`
  );
}

/**
 * What it costs to run without one, said at every start and by `--check`. One place, so the two
 * cannot drift apart.
 */
export const NO_EXECUTOR_KEY = [
  "NO EXECUTOR KEY. Every answer that ends a Distress is signed with the watch key,",
  "which the daemon -- and the agent beside it -- holds too. A phone cannot tell a person's",
  "answer from one the agent made up, so phones keep the old rule and say this watch does",
  "not yet name its escalation key. Set executor_key_path in [identity] (see",
  "escalation.example.toml), start the executor once as its own user, and hand its key to",
  "operators with the watch's.",
];

/** Whether one relay took a test response signed by each key: null when it did, else why not. */
export interface RelayTakes {
  url: string;
  watch: string | null;
  executor: string | null;
}

/**
 * Publishes one test response signed by each key to every relay, and says which relays took which.
 *
 * **A relay that takes the watch key and refuses the executor's is the quiet failure here.** The
 * executor's key is new and has no history, so a relay that limits new keys -- an allowlist, payment,
 * proof of work, web of trust, a rate limit on new keys -- takes the watch key's copies and refuses the
 * executor's own. A phone given the executor key then hears only copies from it, and no `Distress`
 * ends there, while the box looks healthy (`escalation.spec.md`, *Every relay the box uses must take
 * both keys*). The other way round is as bad for every phone not handed the executor key, which hears
 * only the copy.
 *
 * **Sent as the executor sends** [review: box safety]: its own first, then the watch key's copy naming
 * it, both handed to the pool before either is awaited. A relay that refuses the second event of a pair
 * -- a rate limit -- refuses here exactly what it refuses in production, so the check blames the key a
 * Distress would lose rather than the other one.
 *
 * The test is the kind the executor sends: an ephemeral `20912`, addressed to and sealed for the key
 * that signed it, so it is stored nowhere and nobody else can read it.
 */
export async function relaysTakeBoth(pool: SimplePool, urls: readonly string[], watch: Keypair, executor: Keypair): Promise<RelayTakes[]> {
  const unique = [...new Set(urls)];
  const payload: ResponsePayload = {
    type: "escalation-status",
    responder: { kind: "node", callsign: "escalation" },
    text: "Relay check from navcom-escalation --check. Not an emergency.",
    provenance: null,
  };
  const test = (key: Keypair, body: ResponsePayload) =>
    finalizeEvent(
      {
        kind: KIND_RESPONSE,
        created_at: Math.floor(Date.now() / 1000),
        tags: [["p", key.pubkey]],
        content: sealResponse(key.secretKey, key.pubkey, body),
      },
      key.secretKey,
    );
  const own = test(executor, payload);
  const copy = test(watch, watchCopy(payload, own.id));
  const sentOwn = pool.publish(unique, own);
  const sentCopy = pool.publish(unique, copy);
  const [e, w] = await Promise.all([Promise.allSettled(sentOwn), Promise.allSettled(sentCopy)]);
  const why = (r: PromiseSettledResult<string> | undefined) =>
    !r ? "no answer" : r.status === "fulfilled" ? null : String(r.reason instanceof Error ? r.reason.message : r.reason);
  return unique.map((url, i) => ({ url, watch: why(w[i]), executor: why(e[i]) }));
}
